# Baba Is You - DS port (BlocksDS)
BLOCKSDS ?= /opt/blocksds/core

NAME          := baba-is-you-ds
GAME_TITLE    := Baba Is You DS
GAME_SUBTITLE := PSP project port
GAME_AUTHOR   := Nova
GAME_ICON     := icon.png

NITROFSDIR    := nitrofs

include $(BLOCKSDS)/sys/default_makefiles/rom_arm9/Makefile
